apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    database: grafana
    user: postgres
    secureJsonData:
      password: "postgres"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full