{
 "title": "Gauge dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "select municipio from connessioni group by municipio;"
   },
   {
    "name": "sede",
    "label": "Sede",
    "query": "select posizione from connessioni where municipio in ($municipio) group by posizione;"
   }
  ]
 },
 "panels": [
  {
   "title": "Servizi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilizzo dei servizi",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n$__time(starttimestamp),\nsum(duration),\nserviceprofile\nFROM\nconnessioni\nWHERE\n$__timeFilter(starttimestamp) and municipio in ($municipio)\ngroup by duration, starttimestamp, serviceprofile\norder by duration;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Upload/Download",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upload e download totali per municipio e sede",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n$__time(starttimestamp),\nsum(upload) as \"UPLOAD\", \nsum(download) as \"DOWNLOAD\"\nFROM\nconnessioni\nWHERE\n$__timeFilter(starttimestamp) and municipio in ($municipio)\ngroup by starttimestamp;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Connessioni totali",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Durata connessioni per municipio/sede",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "repeat": "municipio",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n$__time(starttimestamp),\nsum(duration),\nmunicipio\nFROM\nconnessioni\nWHERE\n$__timeFilter(starttimestamp) and municipio in ($municipio) and posizione in ($sede)\ngroup by starttimestamp, municipio;\n"
      }
     ]
    }
   ]
  }
 ]
}