{
 "title": "Geo dashboard",
 "time": { "from": "2020-06-23T12:00:00.000Z", "to": "2020-06-30T11:59:58.000Z" },
 "templating": {
  "list": [
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "select municipio from connessioni group by municipio;"
   },
   {
    "name": "sede",
    "label": "Sede",
    "query": "select posizione from connessioni where municipio in ($municipio) group by posizione;"
   }
  ]
 },
 "panels": [
  { "title": "Download diviso per sedi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Medio",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select posizione, longitudine, latitudine, (avg(download)::float / 1000000000::float) as tipologia from connessioni \nwhere municipio in ($municipio) and \nEXTRACT(EPOCH FROM starttimestamp)*1000 >= $__from and EXTRACT(EPOCH FROM endtimestamp)*1000 <= $__to and\nposizione in ($sede)\ngroup by (posizione, longitudine, latitudine);\n"
    }
   ]
  },
  {
   "title": "Totale",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select posizione, longitudine, latitudine, (sum(download)::float / 1000000000::float) as tipologia from connessioni \nwhere municipio in ($municipio) and \nEXTRACT(EPOCH FROM starttimestamp)*1000 >= $__from and EXTRACT(EPOCH FROM endtimestamp)*1000 <= $__to and\nposizione in ($sede)\ngroup by (posizione, longitudine, latitudine);\n"
    }
   ]
  },
  {
   "title": "Picco",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select posizione, longitudine, latitudine, (max(download)::float / 1000000000::float) as tipologia from connessioni \nwhere municipio in ($municipio) and \nEXTRACT(EPOCH FROM starttimestamp)*1000 >= $__from and EXTRACT(EPOCH FROM endtimestamp)*1000 <= $__to and\nposizione in ($sede)\ngroup by (posizione, longitudine, latitudine);\n"
    }
   ]
  },
  { "title": "Upload diviso per sedi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Medio",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select posizione, longitudine, latitudine, (avg(upload)::float / 1000000000::float) as tipologia from connessioni \nwhere municipio in ($municipio) and \nEXTRACT(EPOCH FROM starttimestamp)*1000 >= $__from and EXTRACT(EPOCH FROM endtimestamp)*1000 <= $__to and\nposizione in ($sede)\ngroup by (posizione, longitudine, latitudine);\n"
    }
   ]
  },
  {
   "title": "Totale",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select posizione, longitudine, latitudine, (sum(upload)::float / 1000000000::float) as tipologia from connessioni \nwhere municipio in ($municipio) and \nEXTRACT(EPOCH FROM starttimestamp)*1000 >= $__from and EXTRACT(EPOCH FROM endtimestamp)*1000 <= $__to and\nposizione in ($sede)\ngroup by (posizione, longitudine, latitudine);\n"
    }
   ]
  },
  {
   "title": "Picco",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select posizione, longitudine, latitudine, (max(upload)::float / 1000000000::float) as tipologia from connessioni \nwhere municipio in ($municipio) and \nEXTRACT(EPOCH FROM starttimestamp)*1000 >= $__from and EXTRACT(EPOCH FROM endtimestamp)*1000 <= $__to and\nposizione in ($sede)\ngroup by (posizione, longitudine, latitudine);\n"
    }
   ]
  }
 ]
}