{
 "title": "Graph dashboard",
 "time": { "from": "2020-08-31T12:13:26.199Z", "to": "2020-08-31T13:17:43.474Z" },
 "templating": {
  "list": [
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "select municipio from connessioni group by municipio;"
   },
   {
    "name": "sede",
    "label": "Sede",
    "query": "select posizione from connessioni where municipio in ($municipio) group by posizione;"
   }
  ]
 },
 "panels": [
  {
   "title": "Valori di upload per sede",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(starttimestamp),\n  upload,\n  posizione\nFROM\n  connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio) and posizione in ($sede)\ngroup by posizione, starttimestamp, upload\norder by posizione;"
    }
   ]
  },
  {
   "title": "Valori di download per sede",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(starttimestamp),\n  download,\n  posizione\nFROM\n  connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio) and posizione in ($sede)\ngroup by posizione, starttimestamp, download\norder by posizione;"
    }
   ]
  },
  {
   "title": "Durata totale sessione per sede",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(starttimestamp),\n  duration,\n  posizione\nFROM\n  connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio) and posizione in ($sede)\ngroup by posizione, starttimestamp, duration\norder by posizione;"
    }
   ]
  },
  {
   "title": "Contributo upload per sede",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  starttimestamp AS \"time\",\n  sum(upload),\n  posizione\nFROM connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio) and posizione in ($sede)\nGROUP BY posizione, starttimestamp;"
    }
   ]
  },
  {
   "title": "Contributo download per sede",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  starttimestamp AS \"time\",\n  sum(download),\n  posizione\nFROM connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio) and posizione in ($sede)\nGROUP BY posizione, starttimestamp;"
    }
   ]
  }
 ]
}