{
 "title": "Graph dashboard",
 "time": { "from": "2020-08-10T00:00:00.000Z", "to": "2020-08-28T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "select municipio from connessioni group by municipio;"
   },
   {
    "name": "sede",
    "label": "Sede",
    "query": "select posizione from connessioni where municipio in ($municipio) group by posizione;"
   }
  ]
 },
 "panels": [
  {
   "title": "Durata media sessioni per ogni sede ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(starttimestamp),\n  duration,\n  posizione\nFROM\n  connessioni\nWHERE\n  $__timeFilter(starttimestamp) and posizione in ($sede)\ngroup by posizione, starttimestamp, duration\n"
    }
   ]
  },
  {
   "title": "Valori di upload per municipio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(starttimestamp),\n  upload,\n  municipio\nFROM\n  connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio)\ngroup by municipio, starttimestamp, upload;\n"
    }
   ]
  },
  {
   "title": "Valori di download per municipio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(starttimestamp),\n  download,\n  municipio\nFROM\n  connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio)\ngroup by municipio, starttimestamp, download;\n"
    }
   ]
  }
 ]
}