{
 "title": "Servizi",
 "time": { "from": "2020-08-23T08:34:38.958Z", "to": "2020-09-22T00:37:49.687Z" },
 "templating": {
  "list": [
   {
    "name": "municipio",
    "label": "Municipio",
    "query": "select municipio from connessioni group by municipio;"
   },
   {
    "name": "sede",
    "label": "Sede",
    "query": "select posizione from connessioni where municipio in ($municipio) group by posizione;"
   }
  ]
 },
 "panels": [
  {
   "title": "Andamenti upload/download per servizio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Andamento upload $municipio per servzio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "repeat": "municipio",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  starttimestamp AS \"time\",\n  sum(upload),\n  serviceprofile\nFROM connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio)\nGROUP BY serviceprofile, starttimestamp, upload\norder by starttimestamp;"
    }
   ]
  },
  { "title": "Statistiche per servizio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Durata totale sessioni per municipio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(starttimestamp),\n  sum(duration),\n  serviceprofile\nFROM\n  connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio)\ngroup by duration, starttimestamp,  serviceprofile\norder by serviceprofile;"
    }
   ]
  },
  {
   "title": "Totale traffico upload per servizio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 12 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  starttimestamp AS \"time\",\n  sum(upload),\n  serviceprofile\nFROM connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio)\nGROUP BY serviceprofile, starttimestamp, upload\norder by serviceprofile;"
    }
   ]
  },
  {
   "title": "Totale traffico download per servizio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 12 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  starttimestamp AS \"time\",\n  sum(download),\n  serviceprofile\nFROM connessioni\nWHERE\n  $__timeFilter(starttimestamp) and municipio in ($municipio)\nGROUP BY serviceprofile, starttimestamp, download\norder by serviceprofile;"
    }
   ]
  }
 ]
}