CREATE TABLE connessioni(
   ID             INTEGER  NOT NULL PRIMARY KEY
  ,STARTDATE      DATE  NOT NULL
  ,STARTTIME      VARCHAR(8) NOT NULL
  ,ENDDATE        DATE  NOT NULL
  ,ENDTIME        VARCHAR(8) NOT NULL
  ,DURATION       BIGINT  NOT NULL
  ,DOWNLOAD       BIGINT  NOT NULL
  ,UPLOAD         BIGINT  NOT NULL
  ,DOMAIN         VARCHAR(14) NOT NULL
  ,MUNICIPIO      VARCHAR(14) NOT NULL
  ,SERVICEPROFILE VARCHAR(17) NOT NULL
  ,DTLN           VARCHAR(2) NOT NULL
  ,STARTTIMESTAMP VARCHAR(19) NOT NULL
  ,ENDTIMESTAMP   VARCHAR(19) NOT NULL
  ,POSIZIONE      VARCHAR(55) NOT NULL
  ,LATITUDINE     NUMERIC(18,15) NOT NULL
  ,LONGITUDINE    NUMERIC(18,15) NOT NULL
);

\COPY connessioni FROM '/docker-entrypoint-initdb.d/dataset_connessioni.csv' DELIMITER ',' CSV HEADER;