CREATE TABLE mytable(
   STARTDATE       DATE  NOT NULL PRIMARY KEY
  ,STARTTIME       VARCHAR(8) NOT NULL
  ,ENDDATE         DATE  NOT NULL
  ,ENDTIME         VARCHAR(8) NOT NULL
  ,DURATION        INTEGER  NOT NULL
  ,DOWNLOAD        INTEGER  NOT NULL
  ,UPLOAD          INTEGER  NOT NULL
  ,DOMAIN          VARCHAR(14) NOT NULL
  ,MUNICIPIO       VARCHAR(14) NOT NULL
  ,SERVICEPROFILE  VARCHAR(17) NOT NULL
  ,DTLN            VARCHAR(2) NOT NULL
  ,START_TIMESTAMP VARCHAR(17) NOT NULL
  ,END_TIMESTAMP   VARCHAR(17) NOT NULL
  ,POSIZIONE       VARCHAR(55) NOT NULL
  ,LATITUDINE      NUMERIC(18,15) NOT NULL
  ,LONGITUDINE     NUMERIC(18,15) NOT NULL
);